# Generated by Django 5.1.6 on 2025-03-31 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="VeiculoTeste",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100, verbose_name="Nome")),
            ],
            options={
                "verbose_name": "Veículo de Teste",
                "verbose_name_plural": "Veículos de Teste",
            },
        ),
    ]
