# Generated by Django 4.2.20 on 2025-04-12 07:05

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Setor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("gabinete", "Gabinete"),
                            ("departamento", "Departamento"),
                        ],
                        max_length=20,
                        verbose_name="Tipo",
                    ),
                ),
                (
                    "localizacao",
                    models.CharField(
                        choices=[
                            ("terreo", "Térreo"),
                            ("primeiro_piso", "1° Piso"),
                            ("segundo_piso", "2° Piso"),
                        ],
                        max_length=20,
                        verbose_name="Localização",
                    ),
                ),
                (
                    "horario_abertura",
                    models.TimeField(
                        blank=True, null=True, verbose_name="Horário de Abertura"
                    ),
                ),
                (
                    "horario_fechamento",
                    models.TimeField(
                        blank=True, null=True, verbose_name="Horário de Fechamento"
                    ),
                ),
                (
                    "nome_vereador",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Nome do Vereador",
                    ),
                ),
                (
                    "email_vereador",
                    models.EmailField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="E-mail do Vereador",
                    ),
                ),
                (
                    "nome_local",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Nome do Local",
                    ),
                ),
                (
                    "nome_responsavel",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Nome do Responsável",
                    ),
                ),
                (
                    "funcao",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("assessor_1", "Assessor I"),
                            ("assessor_2", "Assessor II"),
                            ("assessor_3", "Assessor III"),
                            ("assessor_4", "Assessor IV"),
                            ("assessor_5", "Assessor V"),
                            ("assessor_6", "Assessor VI"),
                            ("assessor_7", "Assessor VII"),
                            ("assessor_8", "Assessor VIII"),
                            ("assessor_9", "Assessor IX"),
                            ("assessor_10", "Assessor X"),
                            ("agente_parlamentar", "Agente Parlamentar"),
                            ("Chefe_de_Gabinete", "Chefe de Gabinete"),
                            ("Chefe_de_Departamento", "Chefe de Departamento"),
                            ("outros", "Outros"),
                        ],
                        max_length=21,
                        null=True,
                        verbose_name="Função/Cargo",
                    ),
                ),
                (
                    "horario_entrada",
                    models.TimeField(
                        blank=True, null=True, verbose_name="Horário de Entrada"
                    ),
                ),
                (
                    "horario_saida",
                    models.TimeField(
                        blank=True, null=True, verbose_name="Horário de Saída"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=255, null=True, verbose_name="E-mail"
                    ),
                ),
                ("ativo", models.BooleanField(default=True, verbose_name="Ativo")),
                (
                    "data_criacao",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Data de Criação"
                    ),
                ),
                (
                    "data_atualizacao",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Data de Atualização"
                    ),
                ),
                (
                    "usuario",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="setor_responsavel",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuário",
                    ),
                ),
            ],
            options={
                "verbose_name": "Setor",
                "verbose_name_plural": "Setores",
                "ordering": ["tipo", "localizacao"],
            },
        ),
        migrations.CreateModel(
            name="Visitante",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nome_completo",
                    models.CharField(max_length=100, verbose_name="Nome Completo"),
                ),
                (
                    "nome_social",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Nome Social",
                    ),
                ),
                (
                    "data_nascimento",
                    models.DateField(verbose_name="Data de Nascimento"),
                ),
                (
                    "CPF",
                    models.CharField(
                        max_length=14,
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="CPF deve estar no formato XXX.XXX.XXX-XX",
                                regex="^\\d{3}\\.\\d{3}\\.\\d{3}-\\d{2}$",
                            )
                        ],
                        verbose_name="CPF",
                    ),
                ),
                (
                    "telefone",
                    models.CharField(
                        max_length=15,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Telefone deve estar no formato (XX) XXXXX-XXXX",
                                regex="^\\(\\d{2}\\) \\d{5}-\\d{4}$",
                            )
                        ],
                        verbose_name="Telefone",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, null=True, verbose_name="E-mail"
                    ),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("AC", "Acre"),
                            ("AL", "Alagoas"),
                            ("AP", "Amapá"),
                            ("AM", "Amazonas"),
                            ("BA", "Bahia"),
                            ("CE", "Ceará"),
                            ("DF", "Distrito Federal"),
                            ("ES", "Espírito Santo"),
                            ("GO", "Goiás"),
                            ("MA", "Maranhão"),
                            ("MT", "Mato Grosso"),
                            ("MS", "Mato Grosso do Sul"),
                            ("MG", "Minas Gerais"),
                            ("PA", "Pará"),
                            ("PB", "Paraíba"),
                            ("PR", "Paraná"),
                            ("PE", "Pernambuco"),
                            ("PI", "Piauí"),
                            ("RJ", "Rio de Janeiro"),
                            ("RN", "Rio Grande do Norte"),
                            ("RS", "Rio Grande do Sul"),
                            ("RO", "Rondônia"),
                            ("RR", "Roraima"),
                            ("SC", "Santa Catarina"),
                            ("SP", "São Paulo"),
                            ("SE", "Sergipe"),
                            ("TO", "Tocantins"),
                        ],
                        max_length=2,
                        verbose_name="Estado",
                    ),
                ),
                ("cidade", models.CharField(max_length=100, verbose_name="Cidade")),
                (
                    "bairro",
                    models.CharField(
                        choices=[
                            ("alto_boa_vista", "Alto da Boa Vista"),
                            ("alto_bonito", "Alto Bonito"),
                            ("altamira", "Altamira"),
                            ("amazonia", "Amazônia"),
                            ("alvora", "Alvorá"),
                            ("apoena", "Apoena"),
                            ("amec_ville_jacaranda", "Amec Ville Jacarandá"),
                            ("beira_rio_1", "Beira Rio I"),
                            ("beira_rio_2", "Beira Rio II"),
                            ("belvedere", "Belvedere"),
                            ("betania", "Betânia"),
                            ("brasilia", "Brasília"),
                            ("bom_jesus", "Bom Jesus"),
                            ("caetanopolis", "Caetanópolis"),
                            ("casas_populares_1", "Casas Populares I"),
                            ("casas_populares_2", "Casas Populares II"),
                            ("california", "California"),
                            ("cedere_1", "Cedere I"),
                            ("cedere_2", "Cedere II"),
                            ("centro", "Centro"),
                            ("cidade_jardim", "Cidade Jardim"),
                            ("cidade_nova", "Cidade Nova"),
                            ("chacara_belo_vale", "Chacara Belo Vale"),
                            ("chacara_da_lua", "Chacara da Lua"),
                            ("chacara_das_estrelas", "Chacara das Estrelas"),
                            ("chacara_do_sol", "Chacara do Sol"),
                            ("chacara_do_cacau", "Chacara do Cacau"),
                            ("colonia_paulo_fonteles", "Colônia Paulo Fonteles"),
                            (
                                "conjunto_hab_morar_dias_melhores",
                                "Conjunto Hab Morar Dias Melhores",
                            ),
                            ("da_paz", "Da Paz"),
                            ("dos_mineiros", "Dos Mineiros"),
                            ("distrito_industrial", "Distrito Industrial"),
                            ("esplanada", "Esplanada"),
                            ("esperanca", "Esperança"),
                            ("fap", "FAP"),
                            ("fazenda_santo_antonio", "Fazenda Santo Antônio"),
                            ("fazenda_sao_jose", "Fazenda São José"),
                            ("fazenda_serra_grande", "Fazenda Serra Grande"),
                            ("guanabara", "Guanabara"),
                            ("habitar_feliz", "Habitar Feliz"),
                            ("ipiranga", "Ipiranga"),
                            ("jardim_america", "Jardim América"),
                            ("jardim_canada", "Jardim Canadá"),
                            ("jardim_planalto", "Jardim Planalto"),
                            ("jardim_ipiranga", "Jardim Ipiranga"),
                            ("jardim_novo_horizonte", "Jardim Novo Horizonte"),
                            ("liberdade_1", "Liberdade I"),
                            ("liberdade_2", "Liberdade II"),
                            ("linha_verde", "Linha Verde"),
                            ("loteamento_nova_carajas", "Loteamento Nova Carajás"),
                            (
                                "loteamento_paraiso_maranhaozinho",
                                "Loteamento Paraíso Maranhãozinho",
                            ),
                            ("maranhao", "Maranhão"),
                            ("martini", "Martini"),
                            ("minerios", "Minérios"),
                            ("minas_gerais", "Minas Gerais"),
                            ("mirante_da_serra", "Mirante da Serra"),
                            ("montes_claros", "Montes Claros"),
                            ("morar_dias_melhores", "Morar Dias Melhores"),
                            ("morada_nova", "Morada Nova"),
                            ("nova_capital", "Nova Capital"),
                            ("nova_carajas", "Nova Carajás"),
                            ("nova_esperanca", "Nova Esperança"),
                            ("nova_parauapebas", "Nova Parauapebas"),
                            ("nova_vida", "Nova Vida"),
                            ("nova_vitoria", "Nova Vitória"),
                            ("novo_brasil", "Novo Brasil"),
                            ("novo_horizonte", "Novo Horizonte"),
                            ("novo_tempo", "Novo Tempo"),
                            ("novo_viver", "Novo Viver"),
                            (
                                "nucleo_residencial_servicos_carajas",
                                "Núcleo Residencial e de Serviços Carajás",
                            ),
                            ("nucleo_urbano_carajas", "Núcleo Urbano de Carajás"),
                            ("palmares_1", "Palmares 1"),
                            ("palmares_2", "Palmares 2"),
                            ("paraiso", "Paraíso"),
                            ("parque_das_nacoes", "Parque das Nações"),
                            ("parque_dos_carajas", "Parque dos Carajás"),
                            ("parque_sao_luiz", "Parque São Luiz"),
                            ("parque_verde", "Parque Verde"),
                            ("paulo_fonteles", "Paulo Fonteles"),
                            ("polo_industrial_moveleiro", "Polo Industrial Moveleiro"),
                            ("polo_moveleiro", "Polo Moveleiro"),
                            ("porto_seguro", "Porto Seguro"),
                            ("primavera", "Primavera"),
                            ("raio_do_sol", "Raio do Sol"),
                            ("residencial_bambui", "Residencial Bambuí"),
                            ("residencial_belavista", "Residencial Belavista"),
                            ("rio_verde", "Rio Verde"),
                            ("santa_cruz", "Santa Cruz"),
                            ("santa_luzia", "Santa Luzia"),
                            ("sansao", "Sansão"),
                            ("sao_jose", "São José"),
                            ("sao_lucas", "São Lucas"),
                            ("sao_lucas_1", "São Lucas 1"),
                            ("sao_lucas_2", "São Lucas 2"),
                            ("serra_azul", "Serra Azul"),
                            ("talisma", "Talismã"),
                            ("tropical", "Tropical"),
                            ("uniao", "União"),
                            ("vale_do_sol", "Vale do Sol"),
                            ("vale_dos_carajas", "Vale dos Carajás"),
                            ("vale_dos_sonhos", "Vale dos Sonhos"),
                            ("vila_onalicio_barros", "Vila Onalício Barros"),
                            ("vila_nova", "Vila Nova"),
                            ("vila_rica", "Vila Rica"),
                            ("vila_rio_branco", "Vila Rio Branco"),
                            ("vila_sansao", "Vila Sansão"),
                            ("vila_sao_jose", "Vila São José"),
                            ("zona_rural", "Zona Rural"),
                            ("outros", "Outros"),
                            ("outra_cidade", "Outra cidade"),
                        ],
                        default="outros",
                        max_length=50,
                        verbose_name="Bairro",
                    ),
                ),
                (
                    "foto",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="visitantes/",
                        verbose_name="Foto",
                    ),
                ),
                (
                    "face_id",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="Face ID"
                    ),
                ),
                (
                    "face_registrada",
                    models.BooleanField(default=False, verbose_name="Face Registrada"),
                ),
            ],
            options={
                "verbose_name": "Visitante",
                "verbose_name_plural": "Visitantes",
                "ordering": ["nome_completo"],
            },
        ),
        migrations.CreateModel(
            name="Visita",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "localizacao",
                    models.CharField(
                        choices=[
                            ("terreo", "Térreo"),
                            ("plenario", "Plenário"),
                            ("primeiro_piso", "1° Piso"),
                            ("segundo_piso", "2° Piso"),
                        ],
                        default="terreo",
                        max_length=20,
                        verbose_name="Localização",
                    ),
                ),
                (
                    "objetivo",
                    models.CharField(
                        choices=[
                            ("reuniao", "Reunião"),
                            ("manutencao", "Manutenção"),
                            ("evento", "Evento"),
                            ("entrega_documentos", "Entrega de Documentos"),
                            ("outros", "Outros"),
                        ],
                        default="outros",
                        max_length=20,
                        verbose_name="Objetivo",
                    ),
                ),
                (
                    "observacoes",
                    models.TextField(blank=True, null=True, verbose_name="Observações"),
                ),
                (
                    "data_entrada",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        verbose_name="Data/Hora de Entrada",
                    ),
                ),
                (
                    "data_saida",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Data/Hora de Saída"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("em_andamento", "Em Andamento"),
                            ("finalizada", "Finalizada"),
                            ("cancelada", "Cancelada"),
                        ],
                        default="em_andamento",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "setor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="recepcao.setor",
                        verbose_name="Setor",
                    ),
                ),
                (
                    "visitante",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="recepcao.visitante",
                        verbose_name="Visitante",
                    ),
                ),
            ],
            options={
                "verbose_name": "Visita",
                "verbose_name_plural": "Visitas",
                "ordering": ["-data_entrada"],
            },
        ),
        migrations.CreateModel(
            name="Assessor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nome_responsavel",
                    models.CharField(max_length=100, verbose_name="Nome"),
                ),
                (
                    "funcao",
                    models.CharField(
                        choices=[
                            ("assessor_1", "Assessor I"),
                            ("assessor_2", "Assessor II"),
                            ("assessor_3", "Assessor III"),
                            ("assessor_4", "Assessor IV"),
                            ("assessor_5", "Assessor V"),
                            ("assessor_6", "Assessor VI"),
                            ("assessor_7", "Assessor VII"),
                            ("assessor_8", "Assessor VIII"),
                            ("assessor_9", "Assessor IX"),
                            ("assessor_10", "Assessor X"),
                            ("agente_parlamentar", "Agente Parlamentar"),
                            ("chefe_de_gabinete", "Chefe de Gabinete"),
                            ("outros", "Outros"),
                        ],
                        default="assessor_1",
                        max_length=20,
                        verbose_name="Função",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=100, null=True, verbose_name="E-mail"
                    ),
                ),
                (
                    "horario_entrada",
                    models.TimeField(
                        blank=True, null=True, verbose_name="Horário de Entrada"
                    ),
                ),
                (
                    "horario_saida",
                    models.TimeField(
                        blank=True, null=True, verbose_name="Horário de Saída"
                    ),
                ),
                ("ativo", models.BooleanField(default=True, verbose_name="Ativo")),
                (
                    "data_criacao",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Data de Criação"
                    ),
                ),
                (
                    "data_atualizacao",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Última Atualização"
                    ),
                ),
                (
                    "departamento",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="recepcao.setor",
                        verbose_name="Departamento",
                    ),
                ),
                (
                    "usuario",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assessor",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuário",
                    ),
                ),
            ],
            options={
                "verbose_name": "Assessor",
                "verbose_name_plural": "Assessores",
                "ordering": ["nome_responsavel"],
            },
        ),
    ]
