# Generated by Django 5.2 on 2025-06-06 15:02

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recepcao', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitante',
            name='CEP',
            field=models.CharField(blank=True, max_length=9, null=True, verbose_name='CEP'),
        ),
        migrations.AddField(
            model_name='visitante',
            name='biometric_vector',
            field=models.BinaryField(blank=True, null=True, verbose_name='Vetor Biométrico'),
        ),
        migrations.AddField(
            model_name='visitante',
            name='complemento',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Complemento'),
        ),
        migrations.AddField(
            model_name='visitante',
            name='data_atualizacao',
            field=models.DateTimeField(auto_now=True, verbose_name='Última Atualização'),
        ),
        migrations.AddField(
            model_name='visitante',
            name='data_cadastro',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Data de Cadastro'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='visitante',
            name='logradouro',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Logradouro'),
        ),
        migrations.AddField(
            model_name='visitante',
            name='numero',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Número'),
        ),
        migrations.AlterField(
            model_name='setor',
            name='nome_vereador',
            field=models.CharField(default=1, max_length=100, verbose_name='Nome do Vereador/Responsável'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='visita',
            name='status',
            field=models.CharField(choices=[('agendada', 'Agendada'), ('em_andamento', 'Em Andamento'), ('finalizada', 'Finalizada'), ('cancelada', 'Cancelada')], default='em_andamento', max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='visitante',
            name='face_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Face ID (Legado)'),
        ),
        migrations.AlterField(
            model_name='visitante',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='fotos_visitantes/', verbose_name='Foto'),
        ),
        migrations.AlterField(
            model_name='visitante',
            name='nome_completo',
            field=models.CharField(max_length=255, verbose_name='Nome Completo'),
        ),
    ]
