# Generated by Django 5.2 on 2025-06-06 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recepcao', '0002_visitante_cep_visitante_biometric_vector_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visitante',
            name='biometric_vector',
        ),
        migrations.RemoveField(
            model_name='visitante',
            name='face_id',
        ),
        migrations.RemoveField(
            model_name='visitante',
            name='face_registrada',
        ),
    ]
