# Generated by Django 5.1.6 on 2025-03-13 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recepcao', '0002_remove_setor_ativo_setor_horario_abertura_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='setor',
            options={'ordering': ['nome'], 'verbose_name': 'Setor', 'verbose_name_plural': 'Setores'},
        ),
        migrations.RemoveField(
            model_name='setor',
            name='descricao',
        ),
        migrations.AddField(
            model_name='setor',
            name='ativo',
            field=models.BooleanField(default=True, verbose_name='Ativo'),
        ),
        migrations.AddField(
            model_name='setor',
            name='tipo',
            field=models.CharField(choices=[('gabinete_vereador', 'Gabinete de Vereador'), ('departamento', 'Departamento')], default='departamento', max_length=20, verbose_name='Tipo'),
        ),
    ]
