# Generated by Django 5.1.6 on 2025-03-13 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recepcao', '0003_alter_setor_options_remove_setor_descricao_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='setor',
            name='ativo',
        ),
    ]
