# Generated by Django 5.2 on 2025-06-11 14:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recepcao', '0003_remove_facial_recognition'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitante',
            name='foto_large',
            field=models.ImageField(blank=True, null=True, upload_to='fotos_visitantes/large/', verbose_name='Foto Grande'),
        ),
        migrations.AddField(
            model_name='visitante',
            name='foto_medium',
            field=models.ImageField(blank=True, null=True, upload_to='fotos_visitantes/medium/', verbose_name='Foto Média'),
        ),
        migrations.AddField(
            model_name='visitante',
            name='foto_thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='fotos_visitantes/thumbnail/', verbose_name='Foto Thumbnail'),
        ),
        migrations.AlterField(
            model_name='visitante',
            name='CEP',
            field=models.CharField(blank=True, max_length=9, null=True, validators=[django.core.validators.RegexValidator(message='CEP deve estar no formato 00000-000', regex='^\\d{5}-\\d{3}$')], verbose_name='CEP'),
        ),
        migrations.AlterField(
            model_name='visitante',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='fotos_visitantes/original/', verbose_name='Foto Original'),
        ),
    ]
