# Generated by Django 5.1.6 on 2025-03-17 16:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recepcao', '0004_remove_setor_ativo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setor',
            name='tipo',
            field=models.CharField(choices=[('gabinete_vereador', 'Gabinete'), ('departamento', 'Departamento')], default='departamento', max_length=20, verbose_name='Tipo'),
        ),
        migrations.AlterField(
            model_name='visita',
            name='setor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='recepcao.setor', verbose_name='Setor'),
        ),
    ]
