# Generated by Django 5.2.3 on 2025-06-23 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recepcao', '0004_visitante_foto_large_visitante_foto_medium_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitante',
            name='biometric_vector',
            field=models.JSONField(blank=True, editable=False, null=True, verbose_name='Vetor Biométrico'),
        ),
    ]
