# Generated by Django 5.2.3 on 2025-06-24 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recepcao', '0005_visitante_biometric_vector'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setor',
            name='localizacao',
            field=models.CharField(choices=[('terreo', 'Térreo'), ('plenario', 'Plenário'), ('primeiro_piso', '1° Piso'), ('segundo_piso', '2° Piso')], max_length=20, verbose_name='Localização'),
        ),
    ]
