# Generated by Django 5.2.3 on 2025-06-26 18:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recepcao', '0006_alter_setor_localizacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visita',
            name='visitante',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='recepcao.visitante', verbose_name='Visitante'),
        ),
    ]
