# Generated by Django 5.1.6 on 2025-03-20 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recepcao', '0007_alter_visitante_bairro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visita',
            name='objetivo',
            field=models.CharField(choices=[('reuniao', 'Reunião'), ('entrega', 'Entrega de Documentos'), ('entrega_de_mercadorias', 'Entrega de Mercadorias'), ('entrega_de_alimentos', 'Entrega de Alimentos'), ('servico_de_manutencao_externa', 'Serviço de Manutenção Externa'), ('evento', 'Evento'), ('outros', 'Outros')], default='outros', max_length=40, verbose_name='Objetivo'),
        ),
    ]
