# Generated by Django 5.2.3 on 2025-06-30 21:01

import apps.recepcao.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recepcao', '0007_alter_visita_visitante'),
    ]

    operations = [
        migrations.AddField(
            model_name='setor',
            name='foto',
            field=models.ImageField(blank=True, help_text='Foto do setor/responsável', null=True, upload_to='setores/', verbose_name='Foto'),
        ),
        migrations.AlterField(
            model_name='visita',
            name='visitante',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='recepcao.visitante', verbose_name='Visitante'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='visitante',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to=apps.recepcao.models.get_visitor_upload_path, verbose_name='Foto Original'),
        ),
        migrations.AlterField(
            model_name='visitante',
            name='foto_large',
            field=models.ImageField(blank=True, null=True, upload_to=apps.recepcao.models.get_visitor_upload_path, verbose_name='Foto Grande'),
        ),
        migrations.AlterField(
            model_name='visitante',
            name='foto_medium',
            field=models.ImageField(blank=True, null=True, upload_to=apps.recepcao.models.get_visitor_upload_path, verbose_name='Foto Média'),
        ),
        migrations.AlterField(
            model_name='visitante',
            name='foto_thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to=apps.recepcao.models.get_visitor_upload_path, verbose_name='Foto Thumbnail'),
        ),
    ]
