# Generated by Django 5.1.6 on 2025-03-24 17:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recepcao', '0007_alter_visitante_bairro'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assessor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('funcao', models.CharField(choices=[('assessor_1', 'Assessor I'), ('assessor_2', 'Assessor II'), ('assessor_3', 'Assessor III'), ('assessor_4', 'Assessor IV'), ('assessor_5', 'Assessor V'), ('assessor_6', 'Assessor VI'), ('assessor_7', 'Assessor VII'), ('assessor_8', 'Assessor VIII'), ('assessor_9', 'Assessor IX'), ('assessor_10', 'Assessor X'), ('agente_parlamentar', 'Agente Parlamentar'), ('outros', 'Outros')], max_length=20, verbose_name='Função/Cargo')),
                ('horario_entrada', models.TimeField(verbose_name='Horário de Entrada')),
                ('horario_saida', models.TimeField(verbose_name='Horário de Saída')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('data_atualizacao', models.DateTimeField(auto_now=True, verbose_name='Data de Atualização')),
                ('departamento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='recepcao.setor', verbose_name='Departamento')),
            ],
            options={
                'verbose_name': 'Assessor',
                'verbose_name_plural': 'Assessores',
                'ordering': ['nome'],
            },
        ),
    ]
