# Generated by Django 5.2.3 on 2025-07-04 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recepcao', '0008_add_foto_to_setor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessor',
            name='funcao',
            field=models.CharField(choices=[('assessor_1', 'Assessor I'), ('assessor_2', 'Assessor II'), ('assessor_3', 'Assessor III'), ('assessor_4', 'Assessor IV'), ('assessor_5', 'Assessor V'), ('assessor_6', 'Assessor VI'), ('assessor_7', 'Assessor VII'), ('assessor_8', 'Assessor VIII'), ('assessor_9', 'Assessor IX'), ('assessor_10', 'Assessor X'), ('agente_parlamentar', 'Agente Parlamentar'), ('chefe_de_gabinete', 'Chefe de Gabinete'), ('vereador', 'Vereador'), ('outros', 'Outros')], default='assessor_1', max_length=20, verbose_name='Função'),
        ),
    ]
