# Generated by Django 5.1.6 on 2025-03-25 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recepcao', '0009_assessor_usuario_assessor_email_assessor_ativo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessor',
            name='funcao',
            field=models.CharField(choices=[('assessor_1', 'Assessor I'), ('assessor_2', 'Assessor II'), ('assessor_3', 'Assessor III'), ('assessor_4', 'Assessor IV'), ('assessor_5', 'Assessor V'), ('assessor_6', 'Assessor VI'), ('assessor_7', 'Assessor VII'), ('assessor_8', 'Assessor VIII'), ('assessor_9', 'Assessor IX'), ('assessor_10', 'Assessor X'), ('agente_parlamentar', 'Agente Parlamentar'), ('chefe_de_gabinete', 'Chefe de Gabinete'), ('outros', 'Outros')], max_length=20, verbose_name='Função/Cargo'),
        ),
    ]
