# Generated by Django 5.2.3 on 2025-08-26 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recepcao', '0009_alter_assessor_funcao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setor',
            name='tipo',
            field=models.CharField(choices=[('gabinete', 'Gabinete'), ('gabinete_vereador', 'Gabinete de Vereador'), ('departamento', 'Departamento')], max_length=20, verbose_name='Tipo'),
        ),
        migrations.DeleteModel(
            name='Assessor',
        ),
    ]
