# Generated by Django 5.1.6 on 2025-03-26 17:24

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recepcao', '0009_assessor_usuario_assessor_email_assessor_ativo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='setor',
            name='ativo',
            field=models.BooleanField(default=True, verbose_name='Ativo'),
        ),
        migrations.AddField(
            model_name='setor',
            name='data_atualizacao',
            field=models.DateTimeField(auto_now=True, verbose_name='Data de Atualização'),
        ),
        migrations.AddField(
            model_name='setor',
            name='data_criacao',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Data de Criação'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='setor',
            name='email',
            field=models.EmailField(blank=True, max_length=255, null=True, verbose_name='E-mail'),
        ),
        migrations.AddField(
            model_name='setor',
            name='funcao',
            field=models.CharField(blank=True, choices=[('assessor_1', 'Assessor I'), ('assessor_2', 'Assessor II'), ('assessor_3', 'Assessor III'), ('assessor_4', 'Assessor IV'), ('assessor_5', 'Assessor V'), ('assessor_6', 'Assessor VI'), ('assessor_7', 'Assessor VII'), ('assessor_8', 'Assessor VIII'), ('assessor_9', 'Assessor IX'), ('assessor_10', 'Assessor X'), ('agente_parlamentar', 'Agente Parlamentar'), ('outros', 'Outros')], max_length=20, null=True, verbose_name='Função/Cargo'),
        ),
        migrations.AddField(
            model_name='setor',
            name='horario_entrada',
            field=models.TimeField(blank=True, null=True, verbose_name='Horário de Entrada'),
        ),
        migrations.AddField(
            model_name='setor',
            name='horario_saida',
            field=models.TimeField(blank=True, null=True, verbose_name='Horário de Saída'),
        ),
        migrations.AddField(
            model_name='setor',
            name='nome_responsavel',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nome do Responsável'),
        ),
        migrations.AddField(
            model_name='setor',
            name='usuario',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='setor_responsavel', to=settings.AUTH_USER_MODEL, verbose_name='Usuário'),
        ),
    ]
