# Generated by Django 5.1.6 on 2025-03-27 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recepcao', '0010_alter_assessor_funcao'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitante',
            name='face_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Face ID'),
        ),
    ]
