# Generated by Django 5.1.6 on 2025-03-26 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recepcao', '0010_setor_ativo_setor_data_atualizacao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setor',
            name='funcao',
            field=models.CharField(blank=True, choices=[('assessor_1', 'Assessor I'), ('assessor_2', 'Assessor II'), ('assessor_3', 'Assessor III'), ('assessor_4', 'Assessor IV'), ('assessor_5', 'Assessor V'), ('assessor_6', 'Assessor VI'), ('assessor_7', 'Assessor VII'), ('assessor_8', 'Assessor VIII'), ('assessor_9', 'Assessor IX'), ('assessor_10', 'Assessor X'), ('agente_parlamentar', 'Agente Parlamentar'), ('Chefe_de_Gabinete', 'Chefe de Gabinete'), ('Chefe_de_Departamento', 'Chefe de Departamento'), ('outros', 'Outros')], max_length=21, null=True, verbose_name='Função/Cargo'),
        ),
    ]
