# Generated by Django 5.2.3 on 2025-11-14 17:54

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recepcao', '0010_remove_assessor_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitante',
            name='CPF',
            field=models.CharField(blank=True, max_length=14, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='CPF deve estar no formato XXX.XXX.XXX-XX', regex='^\\d{3}\\.\\d{3}\\.\\d{3}-\\d{2}$')], verbose_name='CPF'),
        ),
        migrations.AlterField(
            model_name='visitante',
            name='bairro',
            field=models.CharField(choices=[('alto_boa_vista', 'Alto da Boa Vista'), ('alto_bonito', 'Alto Bonito'), ('altamira', 'Altamira'), ('amazonia', 'Amazônia'), ('alvora', 'Alvorá'), ('apoena', 'Apoena'), ('amec_ville_jacaranda', 'Amec Ville Jacarandá'), ('beira_rio_1', 'Beira Rio I'), ('beira_rio_2', 'Beira Rio II'), ('belvedere', 'Belvedere'), ('betania', 'Betânia'), ('brasilia', 'Brasília'), ('bom_jesus', 'Bom Jesus'), ('caetanopolis', 'Caetanópolis'), ('casas_populares_1', 'Casas Populares I'), ('casas_populares_2', 'Casas Populares II'), ('california', 'California'), ('cedere_1', 'Cedere I'), ('cedere_2', 'Cedere II'), ('centro', 'Centro'), ('cidade_jardim', 'Cidade Jardim'), ('cidade_nova', 'Cidade Nova'), ('chacara_belo_vale', 'Chacara Belo Vale'), ('chacara_da_lua', 'Chacara da Lua'), ('chacara_das_estrelas', 'Chacara das Estrelas'), ('chacara_do_sol', 'Chacara do Sol'), ('chacara_do_cacau', 'Chacara do Cacau'), ('colonia_paulo_fonteles', 'Colônia Paulo Fonteles'), ('conjunto_hab_morar_dias_melhores', 'Conjunto Hab Morar Dias Melhores'), ('da_paz', 'Da Paz'), ('dos_mineiros', 'Dos Mineiros'), ('distrito_industrial', 'Distrito Industrial'), ('esplanada', 'Esplanada'), ('esperanca', 'Esperança'), ('fap', 'FAP'), ('fazenda_santo_antonio', 'Fazenda Santo Antônio'), ('fazenda_sao_jose', 'Fazenda São José'), ('fazenda_serra_grande', 'Fazenda Serra Grande'), ('guanabara', 'Guanabara'), ('habitar_feliz', 'Habitar Feliz'), ('ipiranga', 'Ipiranga'), ('jardim_america', 'Jardim América'), ('jardim_canada', 'Jardim Canadá'), ('jardim_planalto', 'Jardim Planalto'), ('jardim_ipiranga', 'Jardim Ipiranga'), ('jardim_novo_horizonte', 'Jardim Novo Horizonte'), ('liberdade_1', 'Liberdade I'), ('liberdade_2', 'Liberdade II'), ('linha_verde', 'Linha Verde'), ('loteamento_nova_carajas', 'Loteamento Nova Carajás'), ('loteamento_paraiso_maranhaozinho', 'Loteamento Paraíso Maranhãozinho'), ('maranhao', 'Maranhão'), ('martini', 'Martini'), ('minerios', 'Minérios'), ('minas_gerais', 'Minas Gerais'), ('mirante_da_serra', 'Mirante da Serra'), ('montes_claros', 'Montes Claros'), ('morar_dias_melhores', 'Morar Dias Melhores'), ('morada_nova', 'Morada Nova'), ('nova_capital', 'Nova Capital'), ('nova_carajas', 'Nova Carajás'), ('nova_esperanca', 'Nova Esperança'), ('nova_parauapebas', 'Nova Parauapebas'), ('nova_vida', 'Nova Vida'), ('nova_vitoria', 'Nova Vitória'), ('novo_brasil', 'Novo Brasil'), ('novo_horizonte', 'Novo Horizonte'), ('novo_tempo', 'Novo Tempo'), ('novo_viver', 'Novo Viver'), ('nucleo_residencial_servicos_carajas', 'Núcleo Residencial e de Serviços Carajás'), ('nucleo_urbano_carajas', 'Núcleo Urbano de Carajás'), ('palmares_1', 'Palmares 1'), ('palmares_2', 'Palmares 2'), ('paraiso', 'Paraíso'), ('parque_das_nacoes', 'Parque das Nações'), ('parque_dos_carajas', 'Parque dos Carajás'), ('parque_sao_luiz', 'Parque São Luiz'), ('parque_verde', 'Parque Verde'), ('paulo_fonteles', 'Paulo Fonteles'), ('polo_industrial_moveleiro', 'Polo Industrial Moveleiro'), ('polo_moveleiro', 'Polo Moveleiro'), ('porto_seguro', 'Porto Seguro'), ('primavera', 'Primavera'), ('raio_do_sol', 'Raio do Sol'), ('residencial_bambui', 'Residencial Bambuí'), ('residencial_belavista', 'Residencial Belavista'), ('rio_verde', 'Rio Verde'), ('santa_cruz', 'Santa Cruz'), ('santa_luzia', 'Santa Luzia'), ('sansao', 'Sansão'), ('sao_jose', 'São José'), ('sao_lucas', 'São Lucas'), ('sao_lucas_1', 'São Lucas 1'), ('sao_lucas_2', 'São Lucas 2'), ('serra_azul', 'Serra Azul'), ('talisma', 'Talismã'), ('tropical', 'Tropical'), ('uniao', 'União'), ('vale_do_sol', 'Vale do Sol'), ('vale_dos_carajas', 'Vale dos Carajás'), ('vale_dos_sonhos', 'Vale dos Sonhos'), ('vila_onalicio_barros', 'Vila Onalício Barros'), ('vila_nova', 'Vila Nova'), ('vila_rica', 'Vila Rica'), ('vila_rio_branco', 'Vila Rio Branco'), ('vila_sansao', 'Vila Sansão'), ('vila_sao_jose', 'Vila São José'), ('zona_rural', 'Zona Rural'), ('outros', 'Outros'), ('outra_cidade', 'Outra cidade')], default='OUTROS', max_length=50, verbose_name='Bairro'),
        ),
        migrations.AlterField(
            model_name='visitante',
            name='telefone',
            field=models.CharField(blank=True, max_length=15, null=True, validators=[django.core.validators.RegexValidator(message='Telefone deve estar no formato (XX) XXXXX-XXXX', regex='^\\(\\d{2}\\) \\d{5}-\\d{4}$')], verbose_name='Telefone'),
        ),
        migrations.CreateModel(
            name='VisitanteArquivado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_completo', models.CharField(max_length=255, verbose_name='Nome Completo')),
                ('nome_social', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nome Social')),
                ('data_nascimento', models.DateField(verbose_name='Data de Nascimento')),
                ('CPF', models.CharField(blank=True, max_length=14, null=True, verbose_name='CPF')),
                ('telefone', models.CharField(blank=True, max_length=15, null=True, verbose_name='Telefone')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='E-mail')),
                ('estado', models.CharField(max_length=2, verbose_name='Estado')),
                ('cidade', models.CharField(max_length=100, verbose_name='Cidade')),
                ('bairro', models.CharField(blank=True, max_length=50, null=True, verbose_name='Bairro')),
                ('logradouro', models.CharField(blank=True, max_length=100, null=True, verbose_name='Logradouro')),
                ('numero', models.CharField(blank=True, max_length=10, null=True, verbose_name='Número')),
                ('complemento', models.CharField(blank=True, max_length=50, null=True, verbose_name='Complemento')),
                ('CEP', models.CharField(blank=True, max_length=9, null=True, verbose_name='CEP')),
                ('foto', models.ImageField(blank=True, null=True, upload_to='arquivados/fotos_visitantes/', verbose_name='Foto Original')),
                ('foto_thumbnail', models.ImageField(blank=True, null=True, upload_to='arquivados/fotos_visitantes/', verbose_name='Foto Thumbnail')),
                ('foto_medium', models.ImageField(blank=True, null=True, upload_to='arquivados/fotos_visitantes/', verbose_name='Foto Média')),
                ('foto_large', models.ImageField(blank=True, null=True, upload_to='arquivados/fotos_visitantes/', verbose_name='Foto Grande')),
                ('biometric_vector', models.JSONField(blank=True, null=True, verbose_name='Vetor Biométrico')),
                ('id_original', models.IntegerField(help_text='ID do visitante antes do arquivamento', verbose_name='ID Original')),
                ('data_cadastro_original', models.DateTimeField(verbose_name='Data de Cadastro Original')),
                ('data_arquivamento', models.DateTimeField(auto_now_add=True, verbose_name='Data de Arquivamento')),
                ('usuario_arquivou', models.CharField(max_length=150, verbose_name='Usuário que Arquivou')),
                ('data_exclusao_definitiva', models.DateTimeField(blank=True, null=True, verbose_name='Data de Exclusão Definitiva')),
            ],
            options={
                'verbose_name': 'Visitante Arquivado',
                'verbose_name_plural': 'Visitantes Arquivados',
                'ordering': ['-data_arquivamento'],
                'indexes': [models.Index(fields=['data_arquivamento'], name='recepcao_vi_data_ar_bc9164_idx'), models.Index(fields=['id_original'], name='recepcao_vi_id_orig_190144_idx')],
            },
        ),
        migrations.CreateModel(
            name='VisitaArquivada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_original', models.IntegerField(help_text='ID da visita antes do arquivamento', verbose_name='ID Original')),
                ('nome_setor', models.CharField(help_text='Nome do setor no momento do arquivamento', max_length=255, verbose_name='Nome do Setor')),
                ('localizacao', models.CharField(choices=[('terreo', 'Térreo'), ('plenario', 'Plenário'), ('primeiro_piso', '1° Piso'), ('segundo_piso', '2° Piso')], default='terreo', max_length=20, verbose_name='Localização')),
                ('objetivo', models.CharField(choices=[('reuniao', 'Reunião'), ('manutencao', 'Manutenção'), ('evento', 'Evento'), ('entrega_documentos', 'Entrega de Documentos'), ('outros', 'Outros')], default='outros', max_length=20, verbose_name='Objetivo')),
                ('observacoes', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('data_entrada', models.DateTimeField(verbose_name='Data/Hora de Entrada')),
                ('data_saida', models.DateTimeField(blank=True, null=True, verbose_name='Data/Hora de Saída')),
                ('status', models.CharField(choices=[('agendada', 'Agendada'), ('em_andamento', 'Em Andamento'), ('finalizada', 'Finalizada'), ('cancelada', 'Cancelada')], default='em_andamento', max_length=20, verbose_name='Status')),
                ('data_arquivamento', models.DateTimeField(auto_now_add=True, verbose_name='Data de Arquivamento')),
                ('visitante_arquivado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visitas_arquivadas', to='recepcao.visitantearquivado', verbose_name='Visitante Arquivado')),
            ],
            options={
                'verbose_name': 'Visita Arquivada',
                'verbose_name_plural': 'Visitas Arquivadas',
                'ordering': ['-data_entrada'],
                'indexes': [models.Index(fields=['data_arquivamento'], name='recepcao_vi_data_ar_eebe9b_idx'), models.Index(fields=['id_original'], name='recepcao_vi_id_orig_64216e_idx')],
            },
        ),
    ]
