# Generated by Django 5.1.6 on 2025-03-28 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recepcao', '0011_visitante_face_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitante',
            name='face_registrada',
            field=models.BooleanField(default=False, verbose_name='Face Registrada'),
        ),
    ]
