# Generated by Django 5.1.6 on 2025-03-31 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recepcao', '0011_alter_setor_funcao'),
        ('recepcao', '0012_visitante_face_registrada'),
    ]

    operations = [
    ]
