# Generated by Django 5.1.6 on 2025-03-31 15:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recepcao", "0012_visitante_face_registrada"),
    ]

    operations = [
        migrations.AlterField(
            model_name="assessor",
            name="departamento",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="recepcao.setor",
                verbose_name="Departamento",
            ),
        ),
    ]
