# Generated by Django 5.1.6 on 2025-04-01 21:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recepcao', '0013_alter_assessor_departamento'),
        ('recepcao', '0013_merge_20250331_1229'),
    ]

    operations = [
    ]
