# Generated by Django 4.2.20 on 2025-04-12 06:50

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Veiculo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("placa", models.CharField(max_length=8, verbose_name="Placa")),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("carro", "Carro"),
                            ("moto", "Moto"),
                            ("van", "Van/Utilitário"),
                            ("caminhao", "Caminhão"),
                            ("outro", "Outro"),
                        ],
                        max_length=10,
                        verbose_name="Tipo",
                    ),
                ),
                ("modelo", models.CharField(max_length=50, verbose_name="Modelo")),
                ("cor", models.CharField(max_length=30, verbose_name="Cor")),
                (
                    "data_entrada",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        verbose_name="Data de Entrada",
                    ),
                ),
                (
                    "data_saida",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Data de Saída"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("presente", "No Estacionamento"),
                            ("saida", "Saída Realizada"),
                        ],
                        default="presente",
                        max_length=10,
                        verbose_name="Status",
                    ),
                ),
                (
                    "observacoes",
                    models.TextField(
                        blank=True, default="", verbose_name="Observações"
                    ),
                ),
            ],
            options={
                "verbose_name": "Veículo",
                "verbose_name_plural": "Veículos",
                "ordering": ["-data_entrada"],
            },
        ),
    ]
