# Generated by Django 4.2.20 on 2025-04-12 07:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("recepcao", "0001_initial"),
        ("veiculos", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="veiculo",
            name="visitante",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="veiculos",
                to="recepcao.visitante",
                verbose_name="Visitante",
            ),
        ),
    ]
