# Generated by Django 5.1.6 on 2025-03-31 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('veiculos', '0001_initial'),
    ]

    operations = [
    ]
