# Generated by Django 5.1.6 on 2025-03-03 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('veiculos', '0002_movimentaçãoveiculo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Movimentaçãoveiculo',
        ),
    ]
