# Generated by Django 4.2.20 on 2025-04-30 19:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recepcao', '0001_initial'),
        ('veiculos', '0002_veiculo_visitante'),
    ]

    operations = [
        migrations.AddField(
            model_name='veiculo',
            name='bloqueado',
            field=models.BooleanField(default=False, verbose_name='Bloqueado'),
        ),
        migrations.AddField(
            model_name='veiculo',
            name='data_bloqueio',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data do Bloqueio'),
        ),
        migrations.AddField(
            model_name='veiculo',
            name='motivo_bloqueio',
            field=models.TextField(blank=True, null=True, verbose_name='Motivo do Bloqueio'),
        ),
        migrations.AlterField(
            model_name='veiculo',
            name='status',
            field=models.CharField(choices=[('presente', 'No Estacionamento'), ('saida', 'Saída Realizada'), ('bloqueado', 'Bloqueado')], default='presente', max_length=10, verbose_name='Status'),
        ),
        migrations.CreateModel(
            name='HistoricoVeiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_entrada', models.DateTimeField(verbose_name='Data de Entrada')),
                ('data_saida', models.DateTimeField(blank=True, null=True, verbose_name='Data de Saída')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
                ('veiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historico', to='veiculos.veiculo')),
                ('visitante', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='recepcao.visitante')),
            ],
            options={
                'verbose_name': 'Histórico de Veículo',
                'verbose_name_plural': 'Históricos de Veículos',
                'ordering': ['-data_entrada'],
            },
        ),
    ]
