# Generated by Django 5.1.6 on 2025-03-31 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('veiculos', '0002_auto_20250331_1017'),
    ]

    operations = [
    ]
