# Generated by Django 4.2.20 on 2025-04-30 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veiculos', '0003_veiculo_bloqueado_veiculo_data_bloqueio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='veiculo',
            name='nome_condutor',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nome do Condutor'),
        ),
        migrations.AddField(
            model_name='veiculo',
            name='nome_passageiro',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nome do Passageiro'),
        ),
        migrations.AlterField(
            model_name='veiculo',
            name='cor',
            field=models.CharField(choices=[('amarela', 'Amarela'), ('azul', 'Azul'), ('bege', 'Bege'), ('branca', 'Branca'), ('cinza', 'Cinza'), ('dourada', 'Dourada'), ('grená', 'Grená'), ('laranja', 'Laranja'), ('marrom', 'Marrom'), ('prata', 'Prata'), ('preta', 'Preta'), ('rosa', 'Rosa'), ('roxa', 'Roxa'), ('verde', 'Verde'), ('vermelha', 'Vermelha')], max_length=20, verbose_name='Cor'),
        ),
    ]
