# Generated by Django 5.1.6 on 2025-03-31 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("veiculos", "0003_auto_20250331_1028"),
    ]

    operations = []
