# Generated by Django 5.1.6 on 2025-03-10 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veiculos', '0004_remove_veiculo_status_veiculo_cor_veiculo_modelo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='veiculo',
            name='cor',
            field=models.CharField(choices=[('Amarela', 'Amarela'), ('Azul', 'Azul'), ('Bege', 'Bege'), ('Branca', 'Branca'), ('Cinza', 'Cinza'), ('Dourada', 'Dourada'), ('Grená', 'Grená'), ('Laranja', 'Laranja'), ('Marrom', 'Marrom'), ('Prata', 'Prata'), ('Preta', 'Preta'), ('Rosa', 'Rosa'), ('Roxa', 'Roxa'), ('Verde', 'Verde'), ('Vermelha', 'Vermelha'), ('Fantasia', 'Fantasia')], default='Branca', max_length=20),
        ),
    ]
