# Generated by Django 4.2.20 on 2025-04-30 21:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('veiculos', '0002_popular_historico'),
        ('veiculos', '0004_veiculo_nome_condutor_veiculo_nome_passageiro_and_more'),
    ]

    operations = [
    ]
