# Generated by Django 5.1.6 on 2025-03-31 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("veiculos", "0004_auto_20250331_1047"),
    ]

    operations = [
        migrations.RunSQL(
            "DROP TABLE IF EXISTS veiculos_new_veiculoteste;",
            reverse_sql="""
            CREATE TABLE veiculos_new_veiculoteste (
                id INTEGER PRIMARY KEY AUTOINCREMENT,
                nome VARCHAR(100) NOT NULL
            );
            """
        ),
    ]
