# Generated by Django 5.1.6 on 2025-03-10 18:41

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veiculos', '0005_alter_veiculo_cor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='veiculo',
            name='cor',
            field=models.CharField(choices=[('Amarela', 'Amarela'), ('Azul', 'Azul'), ('Bege', 'Bege'), ('Branca', 'Branca'), ('Cinza', 'Cinza'), ('Dourada', 'Dourada'), ('Grená', 'Grená'), ('Laranja', 'Laranja'), ('Marrom', 'Marrom'), ('Prata', 'Prata'), ('Preta', 'Preta'), ('Rosa', 'Rosa'), ('Roxa', 'Roxa'), ('Verde', 'Verde'), ('Vermelha', 'Vermelha'), ('Fantasia', 'Fantasia')], max_length=15, verbose_name='Cor do Veículo'),
        ),
        migrations.AlterField(
            model_name='veiculo',
            name='horario_entrada',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Horário de Entrada'),
        ),
        migrations.AlterField(
            model_name='veiculo',
            name='horario_saida',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Horário de Saída'),
        ),
        migrations.AlterField(
            model_name='veiculo',
            name='modelo',
            field=models.CharField(max_length=50, verbose_name='Modelo do Veículo'),
        ),
        migrations.AlterField(
            model_name='veiculo',
            name='observacoes',
            field=models.TextField(blank=True, null=True, verbose_name='Observações'),
        ),
        migrations.AlterField(
            model_name='veiculo',
            name='placa',
            field=models.CharField(help_text='Digite a placa no formato antigo (ABC-1234) ou Mercosul (ABC1D23).', max_length=7, unique=True, verbose_name='Placa do Veículo'),
        ),
        migrations.AlterField(
            model_name='veiculo',
            name='responsavel',
            field=models.CharField(max_length=100, verbose_name='Responsável'),
        ),
        migrations.AlterField(
            model_name='veiculo',
            name='tipo',
            field=models.CharField(choices=[('Carro', 'Carro'), ('Moto', 'Moto'), ('Caminhonete', 'Caminhonete'), ('Caminhão', 'Caminhão'), ('Ônibus', 'Ônibus'), ('Outros', 'Outros')], max_length=15, verbose_name='Tipo de Veículo'),
        ),
    ]
