# Generated by Django 5.1.6 on 2025-03-10 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veiculos', '0006_alter_veiculo_cor_alter_veiculo_horario_entrada_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='veiculo',
            name='status',
            field=models.CharField(choices=[('presente', 'Presente no Estacionamento'), ('saida', 'Saída Realizada')], default='presente', max_length=10, verbose_name='Status'),
        ),
    ]
