# Generated by Django 5.1.6 on 2025-03-10 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veiculos', '0007_veiculo_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='veiculo',
            options={'ordering': ['-horario_entrada'], 'verbose_name': 'Veículo', 'verbose_name_plural': 'Veículos'},
        ),
        migrations.AlterField(
            model_name='veiculo',
            name='horario_entrada',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Horário de Entrada'),
        ),
        migrations.AlterField(
            model_name='veiculo',
            name='observacoes',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Observações'),
        ),
        migrations.AlterField(
            model_name='veiculo',
            name='placa',
            field=models.CharField(max_length=8, unique=True, verbose_name='Placa'),
        ),
    ]
