# Generated by Django 5.1.6 on 2025-03-01 04:15

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Veiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placa', models.CharField(max_length=10, unique=True)),
                ('responsavel', models.CharField(max_length=100)),
                ('horario_entrada', models.DateTimeField(default=django.utils.timezone.now)),
                ('horario_saida', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('dentro', 'Dentro'), ('fora', 'Fora')], default='dentro', max_length=10)),
            ],
        ),
    ]
