# Generated by Django 5.1.6 on 2025-02-25 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Setor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
                ('localizacao', models.CharField(max_length=255)),
                ('ramal', models.CharField(max_length=20)),
                ('disponibilidade', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(max_length=50, unique=True)),
                ('tipo', models.CharField(choices=[('ADMIN', 'ADMINISTRADOR'), ('RECEP', 'RECEPCIONISTA')], default='RECEP', max_length=5)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Veiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placa', models.CharField(max_length=10, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Visitante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_completo', models.CharField(max_length=70)),
                ('nome_social', models.CharField(blank=True, max_length=70, null=True)),
                ('data_nascimento', models.DateField(blank=True, null=True)),
                ('cpf', models.CharField(max_length=14, unique=True)),
                ('foto', models.ImageField(upload_to='fotos_visitante/')),
                ('data_registro', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
