# Generated by Django 5.1.6 on 2025-03-01 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_veiculo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Veiculo',
        ),
        migrations.RenameField(
            model_name='visita',
            old_name='data_entrada',
            new_name='data_visita',
        ),
        migrations.RemoveField(
            model_name='visita',
            name='data_saida',
        ),
        migrations.AddField(
            model_name='visita',
            name='hora_saida',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
