# Generated by Django 5.1.6 on 2025-02-25 20:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_setor_usuario_veiculo_visitante_delete_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='setor',
            old_name='localizacao',
            new_name='localização',
        ),
        migrations.RenameField(
            model_name='visitante',
            old_name='cpf',
            new_name='CPF',
        ),
    ]
