# Generated by Django 5.1.6 on 2025-02-28 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_pessoa_setor_usuario_visita_delete_category'),
    ]

    operations = [
    ]
