# Generated by Django 5.1.6 on 2025-03-03 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_delete_veiculo_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='visita',
            old_name='data_visita',
            new_name='data_entrada',
        ),
    ]
