# Generated by Django 5.1.6 on 2025-02-25 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_rename_username_usuario_usuario_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='veiculo',
            name='horario_entrada',
            field=models.DateTimeField(auto_now_add=True, default='2023-01-01 00:00:00'),
            preserve_default=False,
        ),
    ]
