# Generated by Django 5.1.6 on 2025-02-27 21:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_pessoa_delete_visitante'),
    ]

    operations = [
        migrations.CreateModel(
            name='Visitas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_entrada', models.DateTimeField(auto_now_add=True)),
                ('data_saida', models.DateTimeField(blank=True, null=True)),
                ('motivo_visita', models.TextField(blank=True, null=True)),
                ('etiqueta_emitida', models.BooleanField(default=False)),
                ('reconhecimento_facial', models.BooleanField(default=False)),
            ],
        ),
        migrations.DeleteModel(
            name='Veiculo',
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='email',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='telefone',
            field=models.CharField(max_length=20),
        ),
        migrations.AddField(
            model_name='visitas',
            name='pessoa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Visitas', to='main.pessoa'),
        ),
        migrations.AddField(
            model_name='visitas',
            name='setor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Visitas', to='main.setor'),
        ),
    ]
