# Generated by Django 5.1.6 on 2025-03-11 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_remove_visita_descricao_outros_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setor',
            name='localizacao',
            field=models.CharField(
                choices=[
                    ('terreo', 'Térreo'),
                    ('plenarinho', 'Plenarinho/Térreo'),
                    ('primeiro_piso', '1° Piso'),
                    ('segundo_piso', '2° Piso')
                ],
                default='terreo',
                max_length=20,
                verbose_name='Localização'
            ),
        ),
        migrations.AddField(
            model_name='setor',
            name='tipo',
            field=models.CharField(
                choices=[
                    ('gabinete', 'Gabinete'),
                    ('departamento', 'Departamento')
                ],
                default='departamento',
                max_length=20,
                verbose_name='Tipo'
            ),
        ),
    ]
