# Generated by Django 5.1.6 on 2025-03-11 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veiculos', '0008_alter_veiculo_options_alter_veiculo_horario_entrada_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='veiculo',
            name='cor',
            field=models.CharField(choices=[('Amarela', 'Amarela'), ('Azul', 'Azul'), ('Bege', 'Bege'), ('Branca', 'Branca'), ('Cinza', 'Cinza'), ('Dourada', 'Dourada'), ('Grena', 'Grená'), ('Laranja', 'Laranja'), ('Marrom', 'Marrom'), ('Prata', 'Prata'), ('Preta', 'Preta'), ('Rosa', 'Rosa'), ('Roxa', 'Roxa'), ('Verde', 'Verde'), ('Vermelha', 'Vermelha'), ('Fantasia', 'Fantasia')], max_length=15, verbose_name='Cor do Veículo'),
        ),
    ]
