# Generated by Django 5.1.6 on 2025-02-26 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_veiculo_horario_entrada'),
    ]

    operations = [
        migrations.AddField(
            model_name='veiculo',
            name='horario_saida',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='veiculo',
            name='responsavel',
            field=models.CharField(default='2025-02-26 14:30:00', max_length=80),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='usuario',
            name='senha',
            field=models.CharField(max_length=255),
        ),
    ]
