# Generated by Django 5.2.3 on 2025-09-29 16:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('recepcao', '0010_remove_assessor_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gabinete',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Informe o nome completo do(a) vereador(a)', max_length=100, verbose_name='Nome Completo')),
                ('vereador', models.CharField(help_text='Nome de uso público, como ele(a) é mais conhecido(a) pela população', max_length=100, verbose_name='Nome Público')),
                ('telefone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefone')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='E-mail')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('data_atualizacao', models.DateTimeField(auto_now=True, verbose_name='Data de Atualização')),
                ('setor', models.OneToOneField(limit_choices_to={'tipo': 'gabinete_vereador'}, on_delete=django.db.models.deletion.PROTECT, related_name='gabinete', to='recepcao.setor', verbose_name='Setor')),
            ],
            options={
                'verbose_name': 'Gabinete',
                'verbose_name_plural': 'Gabinetes',
                'ordering': ['nome'],
            },
        ),
    ]
