# Generated by Django 5.1.6 on 2025-03-03 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_rename_data_visita_visita_data_entrada'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Pessoa',
            new_name='Visitante',
        ),
        migrations.DeleteModel(
            name='Usuario',
        ),
        migrations.RenameField(
            model_name='visita',
            old_name='pessoa',
            new_name='visitante',
        ),
    ]
