# Generated by Django 5.1.6 on 2025-03-06 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_rename_pessoa_visitante_delete_usuario_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='visita',
            old_name='hora_saida',
            new_name='data_saida',
        ),
    ]
