# Generated by Django 5.1.6 on 2025-03-06 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_rename_hora_saida_visita_data_saida'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visita',
            name='data_saida',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
