# Generated by Django 5.1.6 on 2025-03-10 21:16

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_visitante_foto'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='setor',
            options={'ordering': ['nome'], 'verbose_name': 'Setor', 'verbose_name_plural': 'Setores'},
        ),
        migrations.AlterModelOptions(
            name='visita',
            options={'ordering': ['-data_visita'], 'verbose_name': 'Visita', 'verbose_name_plural': 'Visitas'},
        ),
        migrations.AlterModelOptions(
            name='visitante',
            options={'ordering': ['nome_completo'], 'verbose_name': 'Visitante', 'verbose_name_plural': 'Visitantes'},
        ),
        migrations.RemoveField(
            model_name='setor',
            name='disponibilidade',
        ),
        migrations.RemoveField(
            model_name='setor',
            name='localização',
        ),
        migrations.RemoveField(
            model_name='setor',
            name='ramal',
        ),
        migrations.RemoveField(
            model_name='visita',
            name='data_entrada',
        ),
        migrations.RemoveField(
            model_name='visita',
            name='data_saida',
        ),
        migrations.RemoveField(
            model_name='visita',
            name='etiqueta_emitida',
        ),
        migrations.RemoveField(
            model_name='visita',
            name='motivo_visita',
        ),
        migrations.RemoveField(
            model_name='visita',
            name='reconhecimento_facial',
        ),
        migrations.RemoveField(
            model_name='visita',
            name='setor',
        ),
        migrations.RemoveField(
            model_name='visita',
            name='visitante',
        ),
        migrations.RemoveField(
            model_name='visitante',
            name='data_registro',
        ),
        migrations.AddField(
            model_name='setor',
            name='descricao',
            field=models.TextField(blank=True, null=True, verbose_name='Descrição'),
        ),
        migrations.AddField(
            model_name='setor',
            name='localizacao',
            field=models.CharField(default='A definir', max_length=200, verbose_name='Localização'),
        ),
        migrations.AddField(
            model_name='visita',
            name='data_visita',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data da Visita'),
        ),
        migrations.AddField(
            model_name='visita',
            name='descricao_outros',
            field=models.TextField(blank=True, null=True, verbose_name='Descrição (quando Outros)'),
        ),
        migrations.AddField(
            model_name='visita',
            name='documento',
            field=models.CharField(default='Não informado', max_length=20, verbose_name='Documento'),
        ),
        migrations.AddField(
            model_name='visita',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='E-mail'),
        ),
        migrations.AddField(
            model_name='visita',
            name='horario_saida',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Horário de Saída'),
        ),
        migrations.AddField(
            model_name='visita',
            name='nome_visitante',
            field=models.CharField(default='Visitante não identificado', max_length=100, verbose_name='Nome do Visitante'),
        ),
        migrations.AddField(
            model_name='visita',
            name='objetivo_visita',
            field=models.CharField(choices=[('reuniao', 'Reunião com o Vereador'), ('projeto_lei', 'Discussão de Projetos de Lei'), ('apoio_proposta', 'Apoio a Proposta de Lei'), ('auxilio_encaminhamento', 'Solicitação de Auxílio ou Encaminhamento'), ('apresentacao_projeto', 'Apresentação de Projeto ou Ideia'), ('pedido_apoio', 'Pedido de Apoio a Causa Social'), ('audiencia_publica', 'Participação em Audiência Pública'), ('assinatura_documentos', 'Assinatura de Documentos ou Petições'), ('visita_institucional', 'Visita Institucional ou Educacional'), ('reuniao_assessoria', 'Reunião com Assessoria Parlamentar'), ('denuncias_reclamacoes', 'Recebimento de Denúncias ou Reclamações'), ('evento_comemoracao', 'Participação em Evento ou Comemoração'), ('pedido_visita_obras', 'Pedido de Visita a Obras ou Serviços Públicos'), ('entrevista_imprensa', 'Entrevista de Imprensa'), ('acompanha_demandas', 'Acompanhamento de Demandas da Comunidade'), ('entrega_documentos', 'Entrega de Requerimentos ou Solicitações'), ('consultoria_orientacao', 'Consultoria ou Orientação Jurídica'), ('outros', 'Outros (Especificar)')], default='reuniao', max_length=50, verbose_name='Objetivo da Visita'),
        ),
        migrations.AddField(
            model_name='visita',
            name='observacoes',
            field=models.TextField(blank=True, null=True, verbose_name='Observações'),
        ),
        migrations.AddField(
            model_name='visita',
            name='telefone',
            field=models.CharField(default='(00) 00000-0000', max_length=15, verbose_name='Telefone'),
        ),
        migrations.AlterField(
            model_name='setor',
            name='nome',
            field=models.CharField(max_length=100, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='visitante',
            name='CPF',
            field=models.CharField(default='000.000.000-00', max_length=14, unique=True, verbose_name='CPF'),
        ),
        migrations.AlterField(
            model_name='visitante',
            name='cidade',
            field=models.CharField(default='Não informada', max_length=100, verbose_name='Cidade'),
        ),
        migrations.AlterField(
            model_name='visitante',
            name='data_nascimento',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Data de Nascimento'),
        ),
        migrations.AlterField(
            model_name='visitante',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='E-mail'),
        ),
        migrations.AlterField(
            model_name='visitante',
            name='estado',
            field=models.CharField(choices=[('AC', 'Acre'), ('AL', 'Alagoas'), ('AP', 'Amapá'), ('AM', 'Amazonas'), ('BA', 'Bahia'), ('CE', 'Ceará'), ('DF', 'Distrito Federal'), ('ES', 'Espírito Santo'), ('GO', 'Goiás'), ('MA', 'Maranhão'), ('MT', 'Mato Grosso'), ('MS', 'Mato Grosso do Sul'), ('MG', 'Minas Gerais'), ('PA', 'Pará'), ('PB', 'Paraíba'), ('PR', 'Paraná'), ('PE', 'Pernambuco'), ('PI', 'Piauí'), ('RJ', 'Rio de Janeiro'), ('RN', 'Rio Grande do Norte'), ('RS', 'Rio Grande do Sul'), ('RO', 'Rondônia'), ('RR', 'Roraima'), ('SC', 'Santa Catarina'), ('SP', 'São Paulo'), ('SE', 'Sergipe'), ('TO', 'Tocantins')], default='SP', max_length=2, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='visitante',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='visitantes/', verbose_name='Foto'),
        ),
        migrations.AlterField(
            model_name='visitante',
            name='nome_completo',
            field=models.CharField(default='Não informado', max_length=100, verbose_name='Nome Completo'),
        ),
        migrations.AlterField(
            model_name='visitante',
            name='nome_social',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nome Social'),
        ),
        migrations.AlterField(
            model_name='visitante',
            name='telefone',
            field=models.CharField(default='(00) 00000-0000', max_length=15, verbose_name='Telefone'),
        ),
    ]
