# Generated by Django 5.1.6 on 2025-03-10 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_visita_nome_visitante_alter_visitante_cpf_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setor',
            name='localizacao',
            field=models.CharField(max_length=200, verbose_name='Localização'),
        ),
        migrations.AlterField(
            model_name='visita',
            name='documento',
            field=models.CharField(max_length=20, verbose_name='Documento'),
        ),
        migrations.AlterField(
            model_name='visita',
            name='objetivo_visita',
            field=models.CharField(choices=[('reuniao', 'Reunião com o Vereador'), ('projeto_lei', 'Discussão de Projetos de Lei'), ('apoio_proposta', 'Apoio a Proposta de Lei'), ('auxilio_encaminhamento', 'Solicitação de Auxílio ou Encaminhamento'), ('apresentacao_projeto', 'Apresentação de Projeto ou Ideia'), ('pedido_apoio', 'Pedido de Apoio a Causa Social'), ('audiencia_publica', 'Participação em Audiência Pública'), ('assinatura_documentos', 'Assinatura de Documentos ou Petições'), ('visita_institucional', 'Visita Institucional ou Educacional'), ('reuniao_assessoria', 'Reunião com Assessoria Parlamentar'), ('denuncias_reclamacoes', 'Recebimento de Denúncias ou Reclamações'), ('evento_comemoracao', 'Participação em Evento ou Comemoração'), ('pedido_visita_obras', 'Pedido de Visita a Obras ou Serviços Públicos'), ('entrevista_imprensa', 'Entrevista de Imprensa'), ('acompanha_demandas', 'Acompanhamento de Demandas da Comunidade'), ('entrega_documentos', 'Entrega de Requerimentos ou Solicitações'), ('consultoria_orientacao', 'Consultoria ou Orientação Jurídica'), ('outros', 'Outros (Especificar)')], max_length=50, verbose_name='Objetivo da Visita'),
        ),
        migrations.AlterField(
            model_name='visita',
            name='telefone',
            field=models.CharField(max_length=15, verbose_name='Telefone'),
        ),
        migrations.AlterField(
            model_name='visitante',
            name='cidade',
            field=models.CharField(max_length=100, verbose_name='Cidade'),
        ),
        migrations.AlterField(
            model_name='visitante',
            name='data_nascimento',
            field=models.DateField(verbose_name='Data de Nascimento'),
        ),
        migrations.AlterField(
            model_name='visitante',
            name='estado',
            field=models.CharField(choices=[('AC', 'Acre'), ('AL', 'Alagoas'), ('AP', 'Amapá'), ('AM', 'Amazonas'), ('BA', 'Bahia'), ('CE', 'Ceará'), ('DF', 'Distrito Federal'), ('ES', 'Espírito Santo'), ('GO', 'Goiás'), ('MA', 'Maranhão'), ('MT', 'Mato Grosso'), ('MS', 'Mato Grosso do Sul'), ('MG', 'Minas Gerais'), ('PA', 'Pará'), ('PB', 'Paraíba'), ('PR', 'Paraná'), ('PE', 'Pernambuco'), ('PI', 'Piauí'), ('RJ', 'Rio de Janeiro'), ('RN', 'Rio Grande do Norte'), ('RS', 'Rio Grande do Sul'), ('RO', 'Rondônia'), ('RR', 'Roraima'), ('SC', 'Santa Catarina'), ('SP', 'São Paulo'), ('SE', 'Sergipe'), ('TO', 'Tocantins')], max_length=2, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='visitante',
            name='telefone',
            field=models.CharField(max_length=15, verbose_name='Telefone'),
        ),
    ]
