# Generated by Django 5.1.6 on 2025-03-10 22:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_alter_setor_localizacao_alter_visita_documento_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visita',
            name='descricao_outros',
        ),
        migrations.RemoveField(
            model_name='visita',
            name='documento',
        ),
        migrations.RemoveField(
            model_name='visita',
            name='email',
        ),
        migrations.RemoveField(
            model_name='visita',
            name='nome_visitante',
        ),
        migrations.RemoveField(
            model_name='visita',
            name='objetivo_visita',
        ),
        migrations.RemoveField(
            model_name='visita',
            name='telefone',
        ),
        migrations.AddField(
            model_name='visita',
            name='visitante',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='main.visitante', verbose_name='Visitante'),
        ),
        migrations.AddField(
            model_name='visitante',
            name='descricao_outros',
            field=models.TextField(blank=True, null=True, verbose_name='Descrição (quando Outros)'),
        ),
        migrations.AddField(
            model_name='visitante',
            name='objetivo_visita',
            field=models.CharField(blank=True, choices=[('reuniao', 'Reunião com o Vereador'), ('projeto_lei', 'Discussão de Projetos de Lei'), ('apoio_proposta', 'Apoio a Proposta de Lei'), ('auxilio_encaminhamento', 'Solicitação de Auxílio ou Encaminhamento'), ('apresentacao_projeto', 'Apresentação de Projeto ou Ideia'), ('pedido_apoio', 'Pedido de Apoio a Causa Social'), ('audiencia_publica', 'Participação em Audiência Pública'), ('assinatura_documentos', 'Assinatura de Documentos ou Petições'), ('visita_institucional', 'Visita Institucional ou Educacional'), ('reuniao_assessoria', 'Reunião com Assessoria Parlamentar'), ('denuncias_reclamacoes', 'Recebimento de Denúncias ou Reclamações'), ('evento_comemoracao', 'Participação em Evento ou Comemoração'), ('pedido_visita_obras', 'Pedido de Visita a Obras ou Serviços Públicos'), ('entrevista_imprensa', 'Entrevista de Imprensa'), ('acompanha_demandas', 'Acompanhamento de Demandas da Comunidade'), ('entrega_documentos', 'Entrega de Requerimentos ou Solicitações'), ('consultoria_orientacao', 'Consultoria ou Orientação Jurídica'), ('outros', 'Outros (Especificar)')], max_length=50, null=True, verbose_name='Objetivo da Visita'),
        ),
    ]
