# Generated by Django 5.1.6 on 2025-03-11 16:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_add_setor_fields'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='setor',
            options={'ordering': ['tipo', 'nome'], 'verbose_name': 'Setor', 'verbose_name_plural': 'Setores'},
        ),
        migrations.RemoveField(
            model_name='setor',
            name='descricao',
        ),
        migrations.AddField(
            model_name='setor',
            name='is_vereador',
            field=models.BooleanField(default=False, verbose_name='É Vereador'),
        ),
        migrations.AddField(
            model_name='visitante',
            name='setor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='main.setor', verbose_name='Setor'),
        ),
        migrations.AlterField(
            model_name='setor',
            name='tipo',
            field=models.CharField(choices=[('gabinete_vereador', 'Gabinete de Vereador'), ('departamento', 'Departamento')], default='departamento', max_length=20, verbose_name='Tipo'),
        ),
        migrations.AlterField(
            model_name='visita',
            name='visitante',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='main.visitante', verbose_name='Visitante'),
        ),
        migrations.AlterField(
            model_name='visitante',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='fotos_visitante/', verbose_name='Foto'),
        ),
        migrations.AlterField(
            model_name='visitante',
            name='objetivo_visita',
            field=models.CharField(blank=True, choices=[('reuniao', 'Reunião com o Vereador'), ('projeto_lei', 'Discussão de Projetos de Lei'), ('apoio_proposta', 'Apoio a Proposta de Lei'), ('auxilio_encaminhamento', 'Solicitação de Auxílio ou Encaminhamento'), ('apresentacao_projeto', 'Apresentação de Projeto ou Ideia'), ('pedido_apoio', 'Pedido de Apoio a Causa Social'), ('audiencia_publica', 'Participação em Audiência Pública'), ('assinatura_documentos', 'Assinatura de Documentos ou Petições'), ('visita_institucional', 'Visita Institucional ou Educacional'), ('reuniao_assessoria', 'Reunião com Assessoria Parlamentar'), ('denuncias_reclamacoes', 'Recebimento de Denúncias ou Reclamações'), ('evento_comemoracao', 'Participação em Evento ou Comemoração'), ('pedido_visita_obras', 'Pedido de Visita a Obras ou Serviços Públicos'), ('entrevista_imprensa', 'Entrevista de Imprensa'), ('acompanha_demandas', 'Acompanhamento de Demandas da Comunidade'), ('entrega_documentos', 'Entrega de Requerimentos ou Solicitações'), ('consultoria_orientacao', 'Consultoria ou Orientação Jurídica'), ('outros', 'Outros (Especificar)')], default='visita_institucional', max_length=50, null=True, verbose_name='Objetivo da Visita'),
        ),
    ]
