# Generated by Django 5.1.6 on 2025-03-12 16:01

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_alter_setor_options_remove_setor_descricao_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='visita',
            options={'ordering': ['-data_entrada'], 'verbose_name': 'Visita', 'verbose_name_plural': 'Visitas'},
        ),
        migrations.RemoveField(
            model_name='visita',
            name='data_visita',
        ),
        migrations.RemoveField(
            model_name='visita',
            name='horario_saida',
        ),
        migrations.AddField(
            model_name='visita',
            name='data_entrada',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data de Entrada'),
        ),
        migrations.AddField(
            model_name='visita',
            name='data_saida',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data de Saída'),
        ),
        migrations.AddField(
            model_name='visita',
            name='status',
            field=models.CharField(choices=[('em_andamento', 'Em Andamento'), ('finalizada', 'Finalizada'), ('cancelada', 'Cancelada')], default='em_andamento', max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='visita',
            name='visitante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='visitas', to='main.visitante', verbose_name='Visitante'),
        ),
    ]
