# Generated by Django 5.1.6 on 2025-03-12 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_clean_visitas_data'),
        ('main', '0015_alter_visita_options_remove_visita_data_visita_and_more'),
    ]

    operations = [
    ]
