# Generated by Django 5.1.6 on 2025-03-12 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_merge_20250312_1302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitante',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='visitantes/', verbose_name='Foto'),
        ),
    ]
